#!/usr/bin/env python

import os
import sys
from lca_writer import LCAWriter
from lca_writer.scripts import LCAWriterArgParser

if __name__ == '__main__':
    p = LCAWriterArgParser()
    a = p.parse_args(sys.argv[1:])

    if a.template is not None:
        LCAWriter.save_template(a.template)
    else:
        for x in a.lca_forms:
            lca = LCAWriter(x)
            lca.write_lca(version=a.version)
