#!/usr/bin/env python

import os
import sys
from lca_writer import LCAWriter

if __name__ == '__main__':
    if len(sys.argv) > 1:
        form_path = sys.argv[1]
    else:
        raise Exception('No form path provided.')

    lca = LCAWriter(p)
    lca.write_lca()
